### ISSUE TITLE
Update permissions to allow non-main push access from the public

### ISSUE THREAD

**Issue by kaungst** [HUD-Data-Lab/Data.Exchange.and.Interoperability#2]
Individuals can't create reviewable pull requests without this access

**Comment by HUD-Data-Lab** [comment]
To contribute we will be using the fork and pull method. You can fork the repository, make your changes, and submit a pull request. We will review and merge your changes as soon as possible. You can also comment on other people's pull requests or submit issues. For further information on how to contribute please refer to the contributing guidelines document that will be on GitHub later today.
