### ISSUE TITLE
Recommendation to combine CEParticipation(s) endpoints

### ISSUE THREAD

**Issue by DavidTweedieWellSky** [HUD-Data-Lab/Data.Exchange.and.Interoperability#30]
CEParticipations: This post endpoint should be added to the "CEParticipation" put/delete/get endpoints.

**Comment by Grant-ICF** [comment]
Hello @DavidTweedieWellSky. Can you clarify your recommendation for me?

To my understanding, if we are to create a new CEParticipation record, we would need a new CEParticipationID. So, including the POST in the /ceparticipation/{CEParticipationID} doesn't make sense to me.

I can however see an argument to move the POST into 
```/CEparticipationsummary/{ProjectID}`` since there needs to be a ProjectID associated with the CEParticipationID and that ProjectID needs to already exist.

**Comment by Grant-ICF** [comment]
We believe we resolved this with the current version of the API Reference v0.1.0b15
